env: "local"


storage:
  driver: "postgres"
  host: "localhost"
  port: 5432
  db_name: "sub-aggregator-api"

http_server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  